--- # 应用名称
spring:
  application:
    name: young-sys-api
--- # Nacos配置
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: 'nacos'
      discovery:
        namespace: sub-dev
        group: group-01
      config:
        group: group-01
        namespace: sub-dev
        import-check:
          enabled: true
  profiles:
    #dev-proxy 本地转发网关 dev 开发环境配置
    include: biz,sys-base,sys-repo,sys-swagger #,dev-proxy
  config:
    import:
      - nacos:young-common-share.yml
      - nacos:${spring.application.name}.yml

logging:
  file:
    name: ${spring.application.name}
  level:
    root: info
